#!/bin/env python

# Convert old _userstate_ file to anydbm files

import sys
sys.path.append('../src')
import auth

import dbhash as mydbm
import cPickle as pickle

uspath = '_userstate_'

with open(uspath) as f:
  (users,sessions,invitations) = pickle.load(f)

for u in users:
  u.dssid_uid = None
  u.dssid_name = None
  auth.store_user(u)

idb = mydbm.open('invitations.db', 'c')
for (id, inv) in invitations.items(): idb[id]=pickle.dumps(inv)
idb.close()

sdb = mydbm.open('sessions.db', 'c')
for (id, s) in sessions.items(): sdb[id]=pickle.dumps(s)
sdb.close()
