#!/bin/env python

# Convert old _userstate_ file to anydbm files

import anydbm
import cPickle as pickle

with open('_userstate_') as f:
  (users,sessions,invitations) = pickle.load(f)

def store_user(user):
  users_db[pickle.dumps(user)]=''
  pass

users_db = anydbm.open('uwiki_users', 'c')
for u in users: store_user(u)
users_db.close()

idb = anydbm.open('uwiki_invitations', 'c')
for (id, inv) in invitations.items(): idb[id]=pickle.dumps(inv)
idb.close()

sdb = anydbm.open('uwiki_sessions', 'c')
for (id, s) in sessions.items(): sdb[id]=pickle.dumps(s)
sdb.close()
